// Reference content that is the same for every scan: the per-stage prebiotic
// figures, the nutrition baseline and the source list. The server sends these
// too, but it is a deployed build that may lag behind the app, and none of it
// depends on the photo — so the app bundles its own copy and fills in whatever
// the response is missing. Both files are generated by api/sync_app_content.py.
import nutrition from "./nutrition.json";
import sourceList from "./sources.json";

export const NUTRITION = {
  basis: nutrition.basis,
  medium_banana_g: nutrition.medium_banana_g,
  fiber_daily_value_g: nutrition.fiber_daily_value_g,
  explainer: nutrition.prebiotic_explainer,
  baseline: nutrition.baseline,
};

export const SOURCES = sourceList.sources;

export function prebioticsFor(stage) {
  return nutrition.stages[stage] ?? null;
}

/**
 * Returns the analysis with the reference blocks guaranteed present. A newer
 * server wins where it answers; anything it leaves out comes from the bundle.
 */
export function withReferenceContent(result) {
  const local = prebioticsFor(result?.stage);
  return {
    ...result,
    prebiotics: result?.prebiotics?.level ? result.prebiotics : local ?? result?.prebiotics,
    nutrition: result?.nutrition?.baseline ? result.nutrition : NUTRITION,
    sources: result?.sources?.length ? result.sources : SOURCES,
  };
}
