"""Copies the reference content the app bundles as a fallback.

The result screen prefers whatever /analyze sends, but a deployed server can be
an older build — and these figures never change per scan anyway, so the app
ships its own copy. This script keeps that copy honest: it is generated, never
hand-edited. Run it from api/ after touching banana_nutrition.json or the
source list in banana_stages.md:

    python sync_app_content.py
"""

import json
import pathlib

from banana_content import load_sources

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / "app" / "content"

NOTE = "Generated by api/sync_app_content.py — edit the files in api/, not this one."


def write(name: str, payload: dict) -> None:
    path = OUT / name
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(HERE.parent)}")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)

    nutrition = json.loads((HERE / "banana_nutrition.json").read_text(encoding="utf-8"))
    nutrition["_comment"] = NOTE
    write("nutrition.json", nutrition)

    sources = load_sources(HERE / "banana_stages.md")
    write("sources.json", {"_comment": NOTE, "sources": sources})
    print(f"{len(nutrition['stages'])} stages, {len(sources)} sources")


if __name__ == "__main__":
    main()
